[build]
target = "aarch64-unknown-linux-gnu"

[target.aarch64-unknown-linux-gnu]
linker = "/home/mfrodiguez/Projects/Toolchains/cross-pi-gcc-10.3.0-64/bin/aarch64-linux-gnu-gcc"
rustflags = [
  "-C", "link-arg=--sysroot=/home/mfrodiguez/Projects/Toolchains/cross-pi-gcc-10.3.0-64/aarch64-linux-gnu/libc"
]
